version: "3.8"

services:
  medbot_gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medbot_gui
    network_mode: host
    environment:
      - DISPLAY=:0
      - GDK_BACKEND=x11
      - WEBKIT_FORCE_COMPOSITING_MODE=1
      - MESA_GL_VERSION_OVERRIDE=3.1
      - MESA_GLES_VERSION_OVERRIDE=3.1
    devices:
      - /dev/dri:/dev/dri
      - /dev/vchiq:/dev/vchiq
    group_add:
      - video
      - render
    privileged: true
    restart: always
